infra:
  natsUri: "nats://localhost:4220,nats://localhost:4221,nats://localhost:4222"
  seedPath: "hack/sys-seed.txt"
publish:
  natsUri: "nats://localhost:4220,nats://localhost:4221,nats://localhost:4222"
  seedPath: "hack/seed.txt"
subscribe:
  natsUri: "nats://localhost:4220,nats://localhost:4221,nats://localhost:4222"
  seedPath: "hack/seed.txt"
  sleepTimeInMillis: 5
monitor:
  scheme: "http"
  host: "localhost"
  port: 32822
  account: "demo"
  consumerName: "GRP_MAKER"
  streamName: "USER_TXN"
  pollSeconds: 1
tracing:
  jaeger-url: http://localhost:30268/api/traces
  service-name: natsjs-demo
api:
  host: "localhost"
  port: 50055