infra:
  natsUri: "localhost:32422"
  seedPath: "hack/sys-seed.txt"
publish:
  natsUri: "localhost:32422"
  seedPath: "hack/seed.txt"
subscribe:
  natsUri: "localhost:32422"
  seedPath: "hack/seed.txt"
  sleepTimeInMillis: 3000
monitor:
  scheme: "http"
  host: "localhost"
  port: 32822
  account: "demo"
  consumerName: "GRP_MAKER"
  streamName: "USER_TXN"
  pollSeconds: 1

