nats:
  jetstream:
    enabled: true
    fileStorage:
      enabled: true
      existingClaim: jetstream-pvc
      claimStorageSize: 10Gi
cluster:
  enabled: false
  # Cluster name is required, by default will be release name.
  # name: "nats"
  replicas: 1
auth:
  enabled: true
  basic:
    accounts:
      demo:
        jetstream: enabled        
        users:
        - nkey: UB6WFVVI6BKTAHT5XGS55BONYOE3TDF47ZD7F75YVPABRXJ7XHWZKX2W
          permission:
            publish: 
            - "USER_TXN.maker"
            - "$JS.>"
            subscribe: 
            - "USER_TXN.maker"
            - "_INBOX.>"
        - nkey: UD736QEIGXPHB5CLR4UAPCOEXET6WIKDYWELPIFHJJDJRNKH3SDHZTLT

