// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package verifier

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// TransactionVerifierClient is the client API for TransactionVerifier service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TransactionVerifierClient interface {
	VerifyTransaction(ctx context.Context, in *VerifyTransactionRequest, opts ...grpc.CallOption) (*VerifyTransactionResponse, error)
}

type transactionVerifierClient struct {
	cc grpc.ClientConnInterface
}

func NewTransactionVerifierClient(cc grpc.ClientConnInterface) TransactionVerifierClient {
	return &transactionVerifierClient{cc}
}

func (c *transactionVerifierClient) VerifyTransaction(ctx context.Context, in *VerifyTransactionRequest, opts ...grpc.CallOption) (*VerifyTransactionResponse, error) {
	out := new(VerifyTransactionResponse)
	err := c.cc.Invoke(ctx, "/verifier.TransactionVerifier/VerifyTransaction", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TransactionVerifierServer is the server API for TransactionVerifier service.
// All implementations must embed UnimplementedTransactionVerifierServer
// for forward compatibility
type TransactionVerifierServer interface {
	VerifyTransaction(context.Context, *VerifyTransactionRequest) (*VerifyTransactionResponse, error)
	mustEmbedUnimplementedTransactionVerifierServer()
}

// UnimplementedTransactionVerifierServer must be embedded to have forward compatible implementations.
type UnimplementedTransactionVerifierServer struct {
}

func (UnimplementedTransactionVerifierServer) VerifyTransaction(context.Context, *VerifyTransactionRequest) (*VerifyTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyTransaction not implemented")
}
func (UnimplementedTransactionVerifierServer) mustEmbedUnimplementedTransactionVerifierServer() {}

// UnsafeTransactionVerifierServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TransactionVerifierServer will
// result in compilation errors.
type UnsafeTransactionVerifierServer interface {
	mustEmbedUnimplementedTransactionVerifierServer()
}

func RegisterTransactionVerifierServer(s grpc.ServiceRegistrar, srv TransactionVerifierServer) {
	s.RegisterService(&TransactionVerifier_ServiceDesc, srv)
}

func _TransactionVerifier_VerifyTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransactionVerifierServer).VerifyTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/verifier.TransactionVerifier/VerifyTransaction",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransactionVerifierServer).VerifyTransaction(ctx, req.(*VerifyTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TransactionVerifier_ServiceDesc is the grpc.ServiceDesc for TransactionVerifier service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TransactionVerifier_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "verifier.TransactionVerifier",
	HandlerType: (*TransactionVerifierServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VerifyTransaction",
			Handler:    _TransactionVerifier_VerifyTransaction_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/verifier/verifier.proto",
}
